[[pages]]
path = "pages/Database_Search.py"
name = "Search"
icon = ":house:"

[[pages]]
path = "pages/Visualization_Dashboard.py"
name = "Dashboard"
icon = ":books:"

[[pages]]
path = "pages/Upload_Data.py"
name = "Upload data"
icon = "ğŸ“–"

[[pages]]
path = "pages/Help.py"
name = "Help"
icon = "ğŸ§°"

[[pages]]
path = "pages/About_Us.py"
name = "About us"
icon = "âœï¸"
